#ifndef __TPU_SECURITY_DEF_H__
#define __TPU_SECURITY_DEF_H__

#define AI_MODEL_KEY_SIZE 16
#define AI_MODEL_BLOCK_SIZE 16
#define AI_MODEL_FINGERPRINT_SIZE 32
#define AI_MODEL_TAG_SIZE 16
#define AI_MODEL_NONCE_SIZE 16
#define AI_MODEL_PWD_SIZE 16
#define AI_MODEL_RSA_N_SIZE 256
#define AI_MODEL_RSA_E_SIZE 4

#define AI_MODEL_DIGEST_SIZE 32 // SHA256

#define AI_MODEL_SECRED_ID_SIZE 4

#define AI_MODEL_KEYFILE_MAX_KEYS 32
#define AI_MODEL_KEYFILE_KEYS_BUF_SIZE (AI_MODEL_KEYFILE_MAX_KEYS * 310 + AI_MODEL_BLOCK_SIZE)

#define AI_MODEL_MAX_LOADED_MODEL 6

#endif /* __TPU_SECURITY_DEF_H__ */
