/*
 * Copyright (c) 2019, Bitmain. All rights reserved.
 *
 */
#ifndef __CV_SECURITY_H
#define __CV_SECURITY_H

#include "platform_common_def.h"
#define FABFW_ROM_PSMSK			0x5C

#define SEC_FABFW_HSPERI_S_TZ_S  (SEC_FAB_FIREWALL + 0x0c)
#define     SEC_FABFW_HSPERI_S8_TZ_S_TPU_SRAM  (1 << 8)
#define SEC_FABFW_DDR_M_AR_NS        (SEC_FAB_FIREWALL + 0x14)
#define     SEC_FABFW_DDR_M4_AR_NS_TPU      (1 << 4)
#define SEC_FABFW_DDR_M_AW_NS        (SEC_FAB_FIREWALL + 0x18)
#define     SEC_fABFW_DDR_M4_AW_NS_TPU      (1 << 4)
#define SEC_FABFW_AP_S4_TZ_S         (SEC_FAB_FIREWALL + 0x30)
#define SEC_FABFW_TPU0_M_AR_NS       (SEC_FAB_FIREWALL + 0x34)
#define     SEC_FABFW_TPU0_M2_AR_NS_TDMA    (1 << 2)
#define     SEC_FABFW_TPU0_M3_AR_NS_TPU     (1 << 3)
#define SEC_FABFW_TPU0_M_AW_NS       (SEC_FAB_FIREWALL + 0x38)
#define     SEC_FABFW_TPU0_M2_AW_NS_TDMA    (1 << 2)
#define     SEC_FABFW_TPU0_M3_AW_NS_TPU     (1 << 3)
#define SEC_FABFW_TPU0_S_TZ_S        (SEC_FAB_FIREWALL + 0x3c)
#define     SEC_FABFW_TPU0_S1_TZ_S_DDR_FW    (1 << 1)
#define     SEC_FABFW_TPU0_S2_TZ_S_TDMA_CTRL (1 << 2)
#define     SEC_FABFW_TPU0_S3_TZ_S_TPU_CTRL  (1 << 3)
#define     SEC_FABFW_TPU0_S4_TZ_S_TPU_MEM   (1 << 4)
#define SEC_FABFW_PERI_FW_S_TZ_S (SEC_FAB_FIREWALL + 0x54)
#define     SEC_FABFW_PERI_FW_S_TZ_S_EFUSE (1 << 18)
#define SEC_FABFW_DBGBUS_LOCK (SEC_FAB_FIREWALL + 0x60)



#define SEC_DDR_FW_CTRL0             (SEC_DDR_FIREWALL + 0x00)
#define     SEC_DDR_FW_CTRL0_EN 1
#define     SEC_DDR_FW_CTRL0_SECREGION_EN_SHIFT 16
#define     SEC_DDR_FW_CTRL0_AID_CTRL_REGION_SHIFT 24
#define     SEC_DDR_FW_CTRL0_AID_CTRL_REGION_ALL 0xff
#define SEC_DDR_FW_CTRL1             (SEC_DDR_FIREWALL + 0x04)

#define SEC_DDR_FW_SECREGION_START_0 (SEC_DDR_FIREWALL + 0x08)
#define SEC_DDR_FW_SECREGION_START_1 (SEC_DDR_FIREWALL + 0x0C)
#define SEC_DDR_FW_SECREGION_START_2 (SEC_DDR_FIREWALL + 0x10)
#define SEC_DDR_FW_SECREGION_START_3 (SEC_DDR_FIREWALL + 0x14)
#define SEC_DDR_FW_SECREGION_START_4 (SEC_DDR_FIREWALL + 0x18)
#define SEC_DDR_FW_SECREGION_START_5 (SEC_DDR_FIREWALL + 0x1C)
#define SEC_DDR_FW_SECREGION_START_6 (SEC_DDR_FIREWALL + 0x20)
#define SEC_DDR_FW_SECREGION_START_7 (SEC_DDR_FIREWALL + 0x24)

#define SEC_DDR_FW_SECREGION_END_0   (SEC_DDR_FIREWALL + 0x28)
#define SEC_DDR_FW_SECREGION_END_1   (SEC_DDR_FIREWALL + 0x2C)
#define SEC_DDR_FW_SECREGION_END_2   (SEC_DDR_FIREWALL + 0x30)
#define SEC_DDR_FW_SECREGION_END_3   (SEC_DDR_FIREWALL + 0x34)
#define SEC_DDR_FW_SECREGION_END_4   (SEC_DDR_FIREWALL + 0x38)
#define SEC_DDR_FW_SECREGION_END_5   (SEC_DDR_FIREWALL + 0x3C)
#define SEC_DDR_FW_SECREGION_END_6   (SEC_DDR_FIREWALL + 0x40)
#define SEC_DDR_FW_SECREGION_END_7   (SEC_DDR_FIREWALL + 0x44)

#define SEC_DDR_FW_DIRTY_REGION      (SEC_DDR_FIREWALL + 0x48)
// Dirty_region to 16MB DRAM offset (0x101000000). Skip ATF region.
#define     SEC_DDR_FW_DIRTY_REGION_DEFAULT 0x01000000

#define SEC_DDR_FW_MOBF_KEY1_0       (SEC_DDR_FIREWALL + 0x4C)
#define SEC_DDR_FW_MOBF_KEY1_1       (SEC_DDR_FIREWALL + 0x50)
#define SEC_DDR_FW_MOBF_KEY1_2       (SEC_DDR_FIREWALL + 0x54)
#define SEC_DDR_FW_MOBF_KEY1_3       (SEC_DDR_FIREWALL + 0x58)
#define SEC_DDR_FW_MOBF_KEY2_0       (SEC_DDR_FIREWALL + 0x5C)
#define SEC_DDR_FW_MOBF_KEY2_1       (SEC_DDR_FIREWALL + 0x60)
#define SEC_DDR_FW_MOBF_KEY2_2       (SEC_DDR_FIREWALL + 0x64)
#define SEC_DDR_FW_MOBF_KEY2_3       (SEC_DDR_FIREWALL + 0x68)

#define SEC_DDR_FW_AID_CTRL0         (SEC_DDR_FIREWALL + 0x6C)
#define SEC_DDR_FW_AID_CTRL1         (SEC_DDR_FIREWALL + 0x70)
#define SEC_DDR_FW_AID_CTRL2         (SEC_DDR_FIREWALL + 0x74)
#define SEC_DDR_FW_AID_CTRL3         (SEC_DDR_FIREWALL + 0x78)
#define     SEC_DDR_FW_AID_CTRL_EN_ALL 0x3ff
#define SEC_DDR_FW_AID_MASK0         (SEC_DDR_FIREWALL + 0x7C)
#define SEC_DDR_FW_AID_MASK1         (SEC_DDR_FIREWALL + 0x80)
#define SEC_DDR_FW_AID_MASK2         (SEC_DDR_FIREWALL + 0x84)
#define SEC_DDR_FW_AID_MASK3         (SEC_DDR_FIREWALL + 0x88)

// 4KB alignment
#define SEC_DDR_FW_ADDR_SHIFT 12


#endif /*__CV_SECURITY_H*/
